### ISSUE TITLE
othmanresign: Permission denied

### ISSUE THREAD

**Issue by iYsood** [OthmanAlmutairi/othmanresign#1]
Abdulrhman-MBP:~ xxx$ /Users/xxx/othmanresign/othmanresign "iPhone Distribution: xxx xxx (xxx)"
-bash: /Users/xxx/othmanresign/othmanresign: Permission denied

**Comment by iYsood** [comment]
$ chmod +x /Users/xxx/othmanresign/othmanresign

 it's work (: 💯

**Comment by ctoska** [comment]
close it, lol
